# Generated by Django 3.0.3 on 2020-07-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='food_list',
            fields=[
                ('name', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('unit', models.CharField(max_length=20)),
                ('storage_type', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('expiry_date', models.DateField()),
            ],
        ),
    ]
